version: "3.9"

services:
  app:
    image: my-app:latest
    secrets:
      - source: my-external-secret
        target: db_password

secrets:
  my-external-secret:
    external: true
    name: "aws/prod/db-password" # DSO Docker plugin will resolve this
